version: "3.8"

services:
  app:
    build:
      context: ./app/
    container_name: app
    depends_on:
      - web
    environment:
      NODE_ENV: development
    entrypoint: ["npm", "run", "dev"]
    volumes:
      # The ./app/src dir is mounted in the container
      # which means changes to package.json still require
      # a rebuild. This is intentional to make sure the
      # correct node_modules are installed
      - type: "bind"
        source: "./app/src"
        target: "/app/src"
        volume:
          nocopy: true # don't copy container files to host volume
        read_only: true
  web:
    build:
      context: ./web/
    container_name: web
    environment:
      NODE_ENV: development
      PORT: 7778
    entrypoint: ["npm", "run", "dev"]
    volumes:
      # The ./web/src dir is mounted in the container
      # which means changes to package.json still require
      # a rebuild. This is intentional to make sure the
      # correct node_modules are installed
      - type: "bind"
        source: "./web/src"
        target: "/web/src"
        volume:
          nocopy: true # don't copy container files to host volume
        read_only: true
    ports:
      - target: 7778
        published: 12000
        protocol: tcp
        mode: host
